### ISSUE TITLE
CSS Mobile and auto resize

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#100]
> we may need some js to auto-resize the Iframe(s) (or get scroll bars) as this is unusable on mobiles when many fields.

Side by side view must be reviewed to work on mobiles devices (tablets, smartphones, etc).
Needs to use a responsive approach with css media queries.

Hint: an easy way to test is to reduce browser width/height.

**Comment by infograf768** [comment]
@jreys 
See this movie where window scrollbars are set to maximum
https://www.dropbox.com/s/2ci79ci2ou22lbx/mobileissues.mp4?dl=0

**Comment by infograf768** [comment]
Can you try this:

``` php
diff --git a/administrator/components/com_associations/views/association/tmpl/edit.php b/administrator/components/com_associations/views/association/tmpl/edit.php
index 09aa561..5dae417 100644
--- a/administrator/components/com_associations/views/association/tmpl/edit.php
+++ b/administrator/components/com_associations/views/association/tmpl/edit.php
@@ -24,5 +24,5 @@
        );
 ?>
-<button id="toogle-left-panel" class="btn btn-small" 
+<button id="toogle-left-panel" class="btn btn-small"
        data-show-reference="<?php echo JText::_('COM_ASSOCIATIONS_EDIT_SHOW_REFERENCE'); ?>"
        data-hide-reference="<?php echo JText::_('COM_ASSOCIATIONS_EDIT_HIDE_REFERENCE'); ?>"><?php echo JText::_('COM_ASSOCIATIONS_EDIT_HIDE_REFERENCE'); ?>
@@ -38,5 +38,5 @@
                <iframe id="reference-association" name="reference-association"
                    src="<?php echo JRoute::_($this->editUri . '&task=' . $this->itemType->item . '.edit&id=' . (int) $this->referenceId); ?>"
-                   height="100%" width="400px" scrolling="no"
+                   height="100%" width="400px" overflow-y="auto"
                    data-action="edit"
                    data-item="<?php echo $this->itemType->item; ?>"
@@ -55,5 +55,5 @@
                <iframe id="target-association" name="target-association"
                    src="<?php echo $this->defaultTargetSrc; ?>"
-                   height="100%" width="400px" scrolling="no"
+                   height="100%" width="400px" overflow-y="auto"
                    data-action="<?php echo $this->targetAction; ?>"
                    data-item="<?php echo $this->itemType->item; ?>"
```

If this is fine, we can get rid of the border.
It does not prevent from using media queries to push the target under the Reference on smaller screens.

What do you think?

**Comment by jreys** [comment]
Tried it, works good, so what you are saying is that if I remove the border, the target will be pushed under the reference on smaller screens? Didn't get that quite right

**Comment by andrepereiradasilva** [comment]
is `overflow-y` a html attribute? or a css style ... http://www.w3schools.com/cssref/css3_pr_overflow-y.asp

**Comment by infograf768** [comment]
What I am saying is that as we would get a scrollbar, we do not need the border anymore

``` css
.sidebyside #left-panel .inner-panel {
    border-style: solid;
    border-color: #999999;
    border-width: 0 1px 0 0;
    padding: 0 10px 0 0;
}
```

**Comment by jreys** [comment]
as @andrepereiradasilva told me, if we add

``` css
/* Responsive layout */
@media (min-width: 768px) and (max-width: 979px) {

}
@media (max-width: 767px) {
    .sidebyside .outer-panel {
        float: none;
        width: 100%;
    }

    .sidebyside #left-panel .inner-panel {
        border-width: 0;
        padding: 0;
    }

    .sidebyside #right-panel .inner-panel {
        padding: 0;
    }
}
```

at the end of the .css file, it works as expected
