### ISSUE TITLE
Side by side display in RTL is wrong

### ISSUE THREAD

**Issue by infograf768** [joomla-projects/gsoc16_improved-multi-lingual#82]
Target and Reference should be inverted

![screen shot 2016-08-10 at 11 02 26](https://cloud.githubusercontent.com/assets/869724/17547977/fbf8a5d0-5ee9-11e6-873e-bcca45458ee2.png)

Basically the floats in edit.php should be right instead of left
for

``` css
.sidebyside .outer-panel {
        float: left;
        width: 50%;
    }
and
.target-text {
        float: left;
        width: 30%;
    }
```

But also the padding and border

Use

``` php
if (JFactory::getLanguage()->isRtl())
```
